# Generated by Django 3.0.2 on 2020-05-08 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('emailid', models.CharField(max_length=30, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(choices=[('BBQ chicken', 'BBQ  chicken'), ('Chicken chily', 'Chicken chilly'), ('butter chicken', 'butter chicken'), ('chicken loppy', 'chicken loppy'), ('chicken masala', 'chicken masala')], max_length=30)),
                ('address', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('out of delivery', 'out of delivery'), ('Delivered', 'Delivered')], max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_pratcise.Customer')),
            ],
        ),
    ]
