# Generated by Django 3.0.2 on 2020-05-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_pratcise', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
